server:
  port: 8084
  servlet:
    context-path: /chat
spring:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:abc123456@localhost:27017/chat-service?authSource=admin
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
      ssl:
        enabled: false

  application:
    name: chat-service
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/issuer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}
