server:
  port: 8080

app:
  api-prefix: /api/v1
  web-client-url: lb://auth-service
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2

            # FILE-SERVICE
            - id: file-service
              uri: lb://file-service
              predicates:
                - Path=/api/v1/file/**
              filters:
                - StripPrefix=2

            # SHOES-SERVICE
            - id: shoes-service
              uri: lb://shoes-service
              predicates:
                - Path=/api/v1/shoes/**
              filters:
                - StripPrefix=2
eureka:
  client:
    fetch-registry: true
    registryFetchIntervalSeconds: 5
