server:
  port: 8080

app:
  api-prefix: /api/v1
  web-client-url: lb://auth-service
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway, API-Gateway

        # USER-SERVICE
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway, API-Gateway

        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway, API-Gateway
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

