server:
  port: 8081

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: maidanghung123@gmail.com
    password: tryczhucvaaqhuhw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:mysql://localhost:3306/five_cu?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

mail:
  from: maidanghung123@gmail.com
  service:
    name: 5CU