app:
  bootstrap:
    admin:
      email: admin
      password: admin
      name: Administrator
server:
  port: 8081
  servlet:
    context-path: /auth
spring:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:abc123456@mongodb-broker-api:27017/auth-service?authSource=admin
    redis:
      host: redis-broker-api
      port: 6379
      repositories:
        enabled: false
      ssl:
        enabled: false

  application:
    name: auth-service
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 3600000     # 1 h in milliseconds
        refresh-token:
          expiration: 604800000 # 7 days in milliseconds
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://api-gateway:8080/issuer
  mail:
    host: smtp.gmail.com
    port: 587
    username: leduy8762@gmail.com
    password: kuotybpsrcscipda
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}

expiration-OTP: 300000 # 5 minutes