server:
  port: 8082
  servlet:
    context-path: /file

minio:
  endpoint: http://minio-api:9000
  access-key: admin
  secret-key: admin@2024
  bucket-name: resources
  public-url: http://localhost:9000
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:abc123456@mongodb-broker-api:27017/file-service?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}
