server:
  port: 8083
  servlet:
    context-path: /shoes
spring:
  application:
    name: shoes-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:abc123456@mongodb-broker-api:27017/shoes-service?authSource=admin
    redis:
      host: redis-broker-api
      port: 6379
      repositories:
        enabled: false
      ssl:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}

payment:
  vnPay:
    environment: docker
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 2QQT1QID
    secretKey: BJC128BQDSLL084SV6H0QLOM19CZLMHE
    returnUrl: http://localhost:8778/api/v1/shoes/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
    returnUrlAfterPayment: http://localhost:3000/checkout/success
